### ISSUE TITLE
fatal: destination path './jin' already exists and is not an empty directory.

### ISSUE THREAD

**Issue by rustamspl** [nin-jin/pms-stub#1]
pms-stub@1.0.0 start C:\dev\js\ts\1\pms-stub
> pms "build" "mol/app/todo"

16:00:40  Building [32m'mol/app/todo?env=web&stage=test'[39m
16:00:40 $jin.file.base..require Module (C:/dev/js/ts/1/pms-stub/jin) not found. Search (jin) in repository...
{ type: 'git', url: 'https://github.com/nin-jin/pms-jin.git' }
16:00:41 $jin.file.base..require Installing (C:/dev/js/ts/1/pms-stub/jin) from (https://github.com/nin-jin/pms-jin.git)...
Cloning into 'C:/dev/js/ts/1/pms-stub/jin'...
16:00:45 $jin.file.base..require Module (C:/dev/js/ts/1/pms-stub/jin) not found. Search (jin) in repository...
{ type: 'git', url: 'https://github.com/nin-jin/pms-jin.git' }
16:00:45 $jin.file.base..require Installing (C:/dev/js/ts/1/pms-stub/jin) from (https://github.com/nin-jin/pms-jin.git)...
fatal: destination path 'C:/dev/js/ts/1/pms-stub/jin' already exists and is not an empty directory.
16:00:45 $jin.atom1.._fail Error: Execution of [git clone https://github.com/nin-jin/pms-jin.git C:/dev/js/ts/1/pms-stub/jin] ends with code 128
    at ChildProcess.<anonymous> (C:\dev\js\ts\1\pms-stub\node_modules\pms\index.env=node.stage=release.js:2933:9)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
--fiber--
    at Object.$jin.proxy.apply (C:\dev\js\ts\1\pms-stub\node_modules\pms\index.env=node.stage=release.js:1796:64)
    at Object.<anonymous> (C:\dev\js\ts\1\pms-stub\node_modules\pms\index.env=node.stage=release.js:344:48)
    at jin_trait_instance.$jin.method.$jin.file.base..require (C:\dev\js\ts\1\pms-stub\node_modules\pms\index.env=node.stage=release.js:5457:10)
    at proceedDep (C:\dev\js\ts\1\pms-stub\node_modules\pms\index.env=node.stage=release.js:6572:9)
    at C:\dev\js\ts\1\pms-stub\node_modules\pms\index.env=node.stage=release.js:6634:31
    at Array.map (native)
    at proceedDep (C:\dev\js\ts\1\pms-stub\node_modules\pms\index.env=node.stage=release.js:6634:6)
    at C:\dev\js\ts\1\pms-stub\node_modules\pms\index.env=node.stage=release.js:6634:31
    at Array.map (native)
    at proceedDep (C:\dev\js\ts\1\pms-stub\node_modules\pms\index.env=node.stage=release.js:6634:6)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\app\\nodejs\\node.exe" "C:\\app\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start" "build" "mol/app/todo"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! pms-stub@1.0.0 start: `pms "build" "mol/app/todo"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pms-stub@1.0.0 start script 'pms "build" "mol/app/todo"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pms-stub package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     pms "build" "mol/app/todo"
npm ERR! You can get their info via:
npm ERR!     npm owner ls pms-stub
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\js\ts\1\pms-stub\npm-debug.log

**Comment by rustamspl** [comment]
npm-debug.log:
https://gist.github.com/rustamspl/720bad3bf6c1be41ab25

**Comment by nin-jin** [comment]
Сборщик некорректно обрабатывает появление нового пакета. Повторный запуск должен помочь.
В конце концов можно сделать чекаут соответствующего репозитория руками:

git clone https://github.com/nin-jin/pms-jin.git ./jin
git clone https://github.com/nin-jin/pms-jin2.git ./jin2
git clone https://github.com/nin-jin/pms-node.git ./node

**Comment by nin-jin** [comment]
Сборщик надо переписать, да.

**Comment by rustamspl** [comment]
Сделал указанные git clone.
Ругается  на 
0:54:39 $jin.atom1.._fail Error: D:/dev/ts/start/2/pms-stub/mol/app/todo/-mix/todo.stage=test.view.tree.ts:11:34
 Cannot find name '$jin2_atom_own'.
D:/dev/ts/start/2/pms-stub/mol/app/todo/-mix/todo.stage=test.view.tree.ts:17:34
** Cannot find name '$jin2_atom_own'.**


$jin2_atom_own был удалён в  коммите  https://github.com/nin-jin/pms-jin2/commit/434321c69282cc940090295a47385a50f870620c

Чекаут на этот коммит тоже не помогает:

20:59:44  Building 'mol/app/todo?env=web&stage=test'
20:59:46 $jin.atom1.._fail Error: D:/dev/ts/start/2/pms-stub/mol/app/todo/todo.view.ts:2:6
 Class '$mol_app_todo' incorrectly extends base class '$mol.$mol_app_todo'.
  Types of property 'allCompleted' are incompatible.

Попробовал  сделать и  для mol чекаут на несколько комитов  ранее -не помогло.

Хотелось бы получить какой-то shell/cmd скрипт который всё-таки сможет собирать с нуля рабочий минимальный проект, todomvc к примеру. Или отдельный работоспособный репозиторий.

На работающем проекте уже можно будет разобраться со сборщиком.

**Comment by nin-jin** [comment]
Странно, $jin2_atom_own давно не используется в $mol.

**Comment by nin-jin** [comment]
А, понял, старая версия jin.

**Comment by nin-jin** [comment]
Понял в чём проблема. Сборщик был старой версии. Нужно обновить его до версии 4.3.6:
```
npm update pms
```

**Comment by rustamspl** [comment]
Теперь без ошибок. Спасибо.
